name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Make a new .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "senha"
          envkey_POSTGRES_DB: "students2_test"
          envkey_DATABASE_URL: "postgres://postgres:senha@db_cli:5432/students2_test"
          file_name: ".env.test"
      - name: Run tests
        run: docker compose -f docker-compose-test.yml run node_app_ci_test npm run test
      - name: Build
        run: npm i && npm run build
